export const tier3Cities = [
  "Aligarh", "Ambala", "Amroha", "Anantapur", "Arrah", "Aurangabad (Bihar)",
  "Azamgarh", "Baghpat", "Bahadurgarh", "Balasore", "Ballia", "Banda",
  "Barabanki", "Baramulla", "Baraut", "Basti", "Begusarai", "Bettiah",
  "Bhadohi", "Bharatpur", "Bhilwara", "Bhiwani", "Bijnor", "Bokaro","Bhagalpur",
  "Budaun", "Bulandshahr", "Chhapra", "Churu", "Darbhanga", "Deoria",
  "Dewas", "Dhanbad", "Dhar", "Dholpur", "Dhule", "Dibrugarh",
  "Dimapur", "Etah", "Etawah", "Faizabad (Ayodhya)", "Faridkot",
  "Farrukhabad", "Fatehpur", "Firozabad", "Ghazipur", "Gonda",
  "Gopalganj", "Gorakhpur (outer areas)", "Hajipur", "Hapur",
  "Hardoi", "Hathras", "Hazaribagh", "Hingoli", "Hoshiarpur",
  "Jaunpur", "Jind", "Kaithal", "Kalyani", "Kapurthala",
  "Kasganj", "Katihar", "Khandwa", "Khanna", "Kishanganj",
  "Kohima", "Lakhimpur", "Lalitpur", "Latur", "Madhubani",
  "Mainpuri", "Malda", "Mandi", "Mansa", "Mathura (outer)",
  "Mau", "Medininagar", "Mirzapur", "Modinagar", "Moga",
  "Morena", "Motihari", "Muradnagar", "Muzaffarpur", "Nadiad",
  "Nalgonda", "Narnaul", "Nawada", "Nizamabad", "Orai",
  "Pali", "Pilibhit", "Pithoragarh", "Raebareli", "Raiganj",
  "Rajsamand", "Ramnagar", "Rampur", "Ranchi (outer areas)",
  "Rewa", "Rohtak (outer)", "Sagar", "Saharanpur", "Samastipur",
  "Sambhal", "Satna", "Shahjahanpur", "Shamli", "Siwan",
  "Solan", "Sonipat (outer)", "Sultanpur", "Tezpur", "Tinsukia",
  "Udhampur", "Unnao", "Vidisha"
];